import{S as v,i as c,a as p}from"./assets/vendor-c145bea9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const y of r.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&l(y)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const L=document.querySelector(".form"),d=document.querySelector(".gallery");document.querySelector(".gallery-box");const i=document.querySelector(".loader-top"),m=document.querySelector(".loader-bottom"),n=document.querySelector(".load-image");let a=1,u="",g=40;const f=new v(".gallery a",{nav:!0,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});L.addEventListener("submit",w);n.addEventListener("click",S);async function w(s){if(s.preventDefault(),i.style.display="block",n.style.display="none",a=1,u=s.target.elements.search.value.trim(),!u){d.innerHTML="",c.info({position:"topRight",message:"Error enter any symbols"}),i.style.display="none";return}try{const{data:{hits:t,totalHits:o}}=await h(u,a);t.length>0?(i.style.display="none",d.innerHTML=b(t),f.refresh(),c.success({position:"topRight",message:`We found ${o} photos`}),n.style.display="block"):(d.innerHTML="",c.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})),o<=g&&(n.style.display="none")}catch(t){console.log("Error",t)}finally{i.style.display="none",s.target.reset()}}function h(s,t){return p.defaults.baseURL="https://pixabay.com",p.get("/api/",{params:{key:"41529899-34462864becb6db8698a10d1b",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:40}})}function b(s=[]){return s.reduce((t,o)=>t+`<li class="gallery-item">
        <a href=${o.largeImageURL}>
          <img class="gallery-img" src=${o.webformatURL} alt=${o.tags} />
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${o.likes}</span></p>
          <p>views: <span class="text-value">${o.views}</span></p>
          <p>comments: <span class="text-value">${o.comments}</span></p>
          <p>downloads: <span class="text-value">${o.downloads}</span></p>
        </div>
      </li>`,"")}async function S(s){m.style.display="block",n.style.display="none";const t=document.querySelector(".gallery-item:first-child");if(t){const o=t.getBoundingClientRect().height;try{a+=1;const{data:{hits:l,totalHits:e}}=await h(u,a),r=Math.ceil(e/g);if(n.style.display="block",d.insertAdjacentHTML("beforeend",b(l)),f.refresh(),a===r)return n.style.display="none",c.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(l){console.log(l)}finally{m.style.display="none",window.scrollBy({top:2*o,behavior:"smooth"})}}}window.addEventListener("scroll",q);const q=()=>{const{height:s}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})};
//# sourceMappingURL=commonHelpers.js.map
